name: Build Release APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      
        
      - name: Set version
        id: set-version
        shell: bash
        run: |
          COMMITS=`git rev-list --count HEAD`
          TAGS=`git tag | wc -l`
          VERSION_CODE=$((COMMITS+TAGS))
          echo "Version Code: $VERSION_CODE"
          VERSION_NAME=`git describe --tags --dirty --abbrev=7 || echo "0.0.0"`
          echo "Version Name: $VERSION_NAME"
          echo "versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT    
          echo "versionName=$VERSION_NAME" >> $GITHUB_OUTPUT
      
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Decode keystore
        run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -di > ${{ github.workspace }}/keystore.jks
        
      - name: Build release
        run: >
          ./gradlew assembleRelease
          -PversionCode=${{ steps.set-version.outputs.versionCode }}
          -PversionName=${{ steps.set-version.outputs.versionName }}
          -Pandroid.injected.signing.store.file=${{ github.workspace }}/keystore.jks
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_FILE_PASSWORD }}
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }}
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: Build Artifacts
          path: app/build/outputs/apk
